<a href="https://colab.research.google.com/github/Andre6o6/mlcourse-2019/blob/master/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!wget https://archive.org/download/nf_prize_dataset.tar/nf_prize_dataset.tar.gz

--2019-10-16 10:28:22--  https://archive.org/download/nf_prize_dataset.tar/nf_prize_dataset.tar.gz
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ia800205.us.archive.org/7/items/nf_prize_dataset.tar/nf_prize_dataset.tar.gz [following]
--2019-10-16 10:28:23--  https://ia800205.us.archive.org/7/items/nf_prize_dataset.tar/nf_prize_dataset.tar.gz
Resolving ia800205.us.archive.org (ia800205.us.archive.org)... 207.241.230.25
Connecting to ia800205.us.archive.org (ia800205.us.archive.org)|207.241.230.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 697552028 (665M) [application/octet-stream]
Saving to: ‘nf_prize_dataset.tar.gz’

nf_prize_dataset.ta 100%[===================>] 665.24M  4.03MB/s    in 1m 41s  

2019-10-16 10:30:05 (6.56 MB/s) - ‘nf_prize_dataset.tar.gz’ saved [697552028/697552028]



In [0]:
!tar -xzf nf_prize_dataset.tar.gz
!tar -xf download/training_set.tar

In [11]:
import os
print(len(os.listdir('training_set/')))

with open('training_set/mv_0010218.txt') as f:
  print(f.readlines())

17770
['10218:\n', '899232,3,2004-07-31\n', '1850680,1,2005-09-18\n', '2609870,1,2005-10-18\n', '2625420,2,2004-06-09\n', '1508073,3,2004-12-02\n', '345673,4,2005-08-10\n', '1738910,4,2004-09-21\n', '1826086,3,2004-10-12\n', '2181840,3,2005-09-16\n', '2094905,3,2005-01-29\n', '1634682,4,2005-03-08\n', '136918,5,2004-09-26\n', '2507158,5,2004-11-03\n', '1434636,2,2004-05-01\n', '2192991,3,2004-07-04\n', '410537,4,2005-11-03\n', '774018,5,2004-12-14\n', '1001129,3,2004-10-29\n', '2536101,3,2005-05-25\n', '56531,3,2004-09-17\n', '1433951,4,2005-09-16\n', '1566279,2,2005-10-21\n', '1151116,1,2005-11-05\n', '472483,4,2005-09-06\n', '2637754,1,2004-06-03\n', '49585,1,2003-03-03\n', '883478,3,2005-10-27\n', '727242,1,2005-11-22\n', '40563,4,2005-08-14\n', '1393057,5,2005-02-17\n', '334803,4,2005-11-26\n', '2100210,4,2005-07-14\n', '1503932,2,2005-04-25\n', '2551806,1,2003-04-11\n', '296935,5,2005-08-19\n', '2170930,1,2005-10-06\n', '487240,5,2005-04-28\n', '636262,1,2005-09-12\n', '1685089,4,

In [0]:
import numpy as np

class FactorizationMachine:
    def __init__(self, n, k):
        self.w0 = 0
        self.w = np.zeros(n)
        self.v = np.zeros((n,k))

        #TODO: cache v dot x
        self.x_batch = None
        self.v_dot_x = None
    
    def forward(self, x):
        #Cache
        self.x_batch = x
        self.v_dot_x = x @ self.v
        
        first = x @ self.w
        second = 0.5 * np.sum(np.square(v_dot_x) - np.square(x) @ np.square(self.v), axis=-1)
        y = self.w0 + first + second

    def backward(self, dLdy):
        if self.x_batch is None:
            assert 0, 'Call forward first'

        dydw0 = 1   #FIXME
        dydw = self.x_batch   #FIXME

        dydv = np.array([x.reshape(-1,1) * (self.v_dot_x) - self.v * np.square(x).reshape(-1,1) 
                         for x in self.x_batch])

        #TODO
        
        #Clear cache
        self.x_batch = None
        self.v_dot_x = None

In [32]:
n=3
k=2
x = np.array([[2,1,0], [1,1,1]])
v = np.array([[1,3],
             [0,2],
             [-1,1]])

v0_dot_x = 0
dydv0 = np.zeros(n)
for j in range(n):
    v0_dot_x += x[0,j]*v[j, 0]

for i in range(n):
    dydv0[i] = x[0,i]*v0_dot_x - v[i, 0]*x[0,i]**2

v1_dot_x = 0
dydv1 = np.zeros(n)
for j in range(n):
    v1_dot_x += x[0,j]*v[j, 1]

for i in range(n):
    dydv1[i] = x[0,i]*v1_dot_x - v[i, 1]*x[0,i]**2


v0_dot_x1 = 0
dy1dv0 = np.zeros(n)
for j in range(n):
    v0_dot_x1 += x[1,j]*v[j, 0]

for i in range(n):
    dy1dv0[i] = x[1,i]*v0_dot_x1 - v[i, 0]*x[1,i]**2

v1_dot_x1 = 0
dy1dv1 = np.zeros(n)
for j in range(n):
    v1_dot_x1 += x[1,j]*v[j, 1]

for i in range(n):
    dy1dv1[i] = x[1,i]*v1_dot_x1 - v[i, 1]*x[1,i]**2

print(dydv0)
print(dydv1)
print(dy1dv0)
print(dy1dv1)

[0. 2. 0.]
[4. 6. 0.]
[-1.  0.  1.]
[3. 4. 5.]


In [0]:
x * (x @ v) - v * np.square(x)

In [87]:
for _x in x:
  print(_x.reshape(-1,1) * (_x @ v) - v * np.square(_x).reshape(-1,1))

np.array([_x.reshape(-1,1) * (_x @ v) - v * np.square(_x).reshape(-1,1) 
          for _x in x])

[[0 4]
 [2 6]
 [0 0]]
[[-1  3]
 [ 0  4]
 [ 1  5]]


array([[[ 0,  4],
        [ 2,  6],
        [ 0,  0]],

       [[-1,  3],
        [ 0,  4],
        [ 1,  5]]])